# Generated by Django 3.2 on 2021-04-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booleanbeanblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
