# Generated by Django 3.2 on 2021-04-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booleanbeanblog', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(),
        ),
    ]
